01_decouverte_micropython: small fixes and additions
prologin/gcc-resources pull request #40
Opened 2020-12-05 20:52 UTC by Nhqml

Fix some typos and add more explanations about conditions (especially
about the `elif` keyword).

2020-12-05 20:57 UTC, Nhqml commented
Also I noticed some special characters (such as: è, é, à) are not rendered in the final pdf. However I could not understand why is that because *it works on my machine* :shrug:

2020-12-06 14:16 UTC, Nhqml commented
Alright so I've investigated this problem, it seems that the version of `latexmk` (provided by `texlive-full` package) is kinda old (2015, WTF is that?). I believe this is what causes the special characters issue.

The only workaround I've found (since I don't think we're able to bump the version) is to write theses characters the *old way*, meaning that in order to get an `è` we would need to type ```\`e```. I'm working on doing this right now, a commit will follow soon.

2020-12-09 22:54 UTC, Elfikurr requested changes
J'ai pas testé si ça s'affiche bien quand on le make, mais je pense que tu l'as fait. :)

Au pire on verra quand Travis le deploy.

Merci en tout cas !

2020-12-09 22:54 UTC, Elfikurr commented on 01_decouverte_micropython/01_decouverte_micropython.md
> +était fausse. Enfin, il y a aussi le `elif` qui est la contraction du `else` et
s/était/est/
Je pense aussi qu'il faudrait rajouter une phrase un tout petit peu plus claire sur le elif, plus que "c'est un else et un if"

2020-12-09 22:54 UTC, Elfikurr commented on 01_decouverte_micropython/01_decouverte_micropython.md
> +elif x < 80:
Peut-être rajouter un autre elif, pour montrer qu'on peut en avoir plusieurs ?
Ou alors en parler au dessus.

2020-12-11 14:50 UTC, Elfikurr approved these changes

2020-12-12 08:09 UTC, merged