Refonte TPs Girls Can Code
prologin/gcc-resources pull request #74
Opened 2022-07-08 12:15 UTC by Gregoire-perso

Refonte Hugo

2022-07-08 14:35 UTC, kolowy approved these changes

2022-07-08 17:36 UTC, amelie311098 requested changes
Quelques typo
Des fichiers qui sont supprimés qui le devraient peut être pas
J'ai pas encore run en local pour vérifier que tout fonctionne bien, j'attendrai la 2e PR

2022-07-08 19:44 UTC, Gregoire-perso commented on README.md
> +objet.
Je l'ai probablement ajouté par réflexe sans y faire attention

2022-07-08 19:53 UTC, Gregoire-perso commented on README.md
> +Pour lancer le site en local, il suffit dhugo server --renderToDisk --noHTTPCachee faire
Oops, va falloir que j'apprenne à utiliser Vim visiblement :P

2022-07-08 20:04 UTC, Gregoire-perso commented on 04_objet/ref.py
> -red = "\033[0;31m"
C'est un fail git ^^

2022-07-08 20:07 UTC, Gregoire-perso commented on 04_web_boni/04_web_boni.md
> ----
Il a été renommé lui pourtant

2022-07-08 20:08 UTC, Gregoire-perso commented on 04_web_boni/04_web.md
> ----
Il était en doublons (c'est le sujet du `04_web` pas bonus)

2022-07-08 20:10 UTC, Gregoire-perso commented on 04_web_boni/source/background/css/style.css
> -html { /* Applique le fond "planche de bois" sur toute la page */
Lui aussi c'est un doublons du `04_web` pas bonus

2022-07-10 15:57 UTC, Nhqml commented
Plusieurs points :
- je suis d'accord avec Amélie, il y a peut-être des fichiers qui sont supprimés alors qu'ils ne devraient pas l'être ?
- cdn.mathjax.org n'existe plus (cf https://www.mathjax.org/cdn-shutting-down/) peut-être qu'il faudrait considérer changer de CDN ?
- la fonctionnalité de copie du code (qui est vraiment très cool btw !) utilise des fonctions dépréciées ([`document.queryCommandSupported()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/queryCommandSupported) et [`document.execCommand()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand)), ce qui veut dire que ça arrêtera de fonctionner un jour... Il faudrait peut-être considérer utiliser l'[API Clipboard](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API) qui semble être la remplaçante ?

Là je pinaille un peu :
- d'un point de vue purement esthétique, j'ai l'impression qu'il y a quelques problèmes de padding/margin, je l'ai notamment constaté sur les titres (quand on clique sur un titre dans la TOC, ça scrolle jusqu'à ce qu'il soit collé au bord haut de l'écran, ajouter un peu de padding serait plus joli)

De manière générale, on a quelques problèmes de rendu sur les TP, etc. mais je suis confiant sur le fait que ça ira mieux une fois que ces derniers auront été adaptés :wink: 

Globalement ça semble prometteur, il y a encore quelques détails à régler mais ça devrait rendre bien un fois fini !

2022-07-16 15:13 UTC, closed without merging

2022-07-16 15:13 UTC, Nhqml commented
Replaced by #76 (which has a cleaner git history)